default = "nbg1"

[[location]]
name = "nbg1"
description = "Nuremberg: Germany, France, Spain, Italy, Netherlands, Switzerland, UK..."

[[location]]
name = "fsn1"
description = "Falkenstein: Germany, France, Spain, Italy, Netherlands, Switzerland, UK..."

[[location]]
name = "hel1"
description = "Helsinki: Finland, Sweden, Norway..."

[[location]]
name = "ash"
description = "Ashburn: US/Miami, Canada/Toronto..."

[[location]]
name = "hil"
description = "Hillsboro: US/Washington, US/Seatle, Canada/Vancouver..."
