default = "debian"

[[os]]
name = "debian-11"
description = "Linux, Debian 11, Bullseye"
default = true

[[os]]
name = "ubuntu-18.04"
description = "Linux, Ubuntu 18.04"
default = false

[[os]]
name = "ubuntu-20.04"
description = "Linux, Ubuntu 20.04"
default = false

[[os]]
name = "ubuntu-22.04"
description = "Linux, Ubuntu 22.04"
default = false

[[os]]
name = "fedora-36"
description = "Linux, Fedora 36"
default = false

[[os]]
name = "centos-stream-8"
description = "Linux, CentOS Stream 8"
default = false

[[os]]
name = "centos-stream-9"
description = "Linux, CentOS Stream 9"
default = false

[[os]]
name = "rocky-8"
description = "Linux, Rocky 8"
default = false

[[os]]
name = "rocky-9"
description = "Linux, Rocky 9"
default = false

